### ISSUE TITLE
App not building on toolchain 46.0 f7

### ISSUE THREAD

**Issue by doomwastaken** [polarikus/flipper-zero_fn_tester#17]
**Окружение**
Модель ФН: (Например ФН-1 (13 мес) ООО "РИК") 
-
Версия приложения: (Версия указана в разделе About)
0.95.0-rc

**Кейс воспроизведения**
Шаги для воспроизведения проблемы:
Не работает сборка приложения в каталоге, необходимо внести изменения в коде и поправить хеш коммита в каталоге.

**Ожидаемое поведение**
Сборка проходит и мы все счастливы :)

**Фактическое поведение**
Warning от компиллятора при сборке. Ошибки линтера игнорируем, а вот warning от компиллятора считаются за ошибки

**Скриншоты**
-

**Дополнительно**
Логов нет, завтра приедет свежая версия каталога, тогда заново можем триггернуть. Проще всего проверить приложение и его сборку через ufbt. Если есть вопросы, обращайтесь

**Comment by polarikus** [comment]
Я в курсе проблемы, они начались у меня еще на develop ветке, разработчики убрали части freeRtos из публичного api, + добавили некоторые флаги к компилятору. Я уже работаю над исправлением и запушу изменения как только rc превратиться в release

**Comment by doomwastaken** [comment]
Там есть пара issues с 0.95.0, думаю не раньше понедельника сможем релизнуть, если в 0.95.1 ничего нового не найдем. Спасибо
